
/************************************************************************************
*                                                                                   *
*   Copyright (c) 2024 Xiaoqiang <username_nullptr@163.com>                         *
*                                                                                   *
*   This file is part of LIBGS                                                      *
*   License: MIT License                                                            *
*                                                                                   *
*   Permission is hereby granted, free of charge, to any person obtaining a copy    *
*   of this software and associated documentation files (the "Software"), to deal   *
*   in the Software without restriction, including without limitation the rights    *
*   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       *
*   copies of the Software, and to permit persons to whom the Software is           *
*   furnished to do so, subject to the following conditions:                        *
*                                                                                   *
*   The above copyright notice and this permission notice shall be included in      *
*   all copies or substantial portions of the Software.                             *
*                                                                                   *
*   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      *
*   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        *
*   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     *
*   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          *
*   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   *
*   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE   *
*   SOFTWARE.                                                                       *
*                                                                                   *
*************************************************************************************/

#include "mime_type.h"
#include "base.h"

#include <unordered_map>
#include <fstream>

namespace libgs
{

#define APPLICATION  "application/"
#define AUDIO        "audio/"
#define CHEMICAL     "chemical/"
#define IMAGE        "image/"
#define INODE        "inode/"
#define MESSAGE      "message/"
#define MODEL        "model/"
#define MULTIPART    "multipart/"
#define TEXT         "text/"
#define VIDEO        "video/"
#define INTERFACE    "interface"

static const std::unordered_map<std::string, std::string> g_suffix_hash
{
	{ ".1"             , TEXT "troff"                                                                  },
	{ ".3ds"           , IMAGE "x-3ds"                                                                 },
	{ ".3fr"           , IMAGE "x-raw-hasselblad"                                                      },
	{ ".3g2"           , VIDEO "3gpp2"                                                                 },
	{ ".3gp"           , VIDEO "3gpp"                                                                  },
	{ ".3mf"           , APPLICATION "vnd.ms-package.3dmanufacturing-3dmodel+xml"                      },
	{ ".4th"           , TEXT "x-forth"                                                                },
	{ ".669"           , AUDIO "x-mod"                                                                 },
	{ ".6pl"           , TEXT "x-perl"                                                                 },
	{ ".7z"            , APPLICATION "x-7z-compressed"                                                 },
	{ ".8svx"          , AUDIO "8svx"                                                                  },
	{ ".ML"            , TEXT "x-ocaml"                                                                },
	{ ".MYD"           , APPLICATION "x-mysql-misam-data"                                              },
	{ ".MYI"           , APPLICATION "x-mysql-misam-compressed-index"                                  },
	{ ".R"             , TEXT "x-rsrc"                                                                 },
	{ ".TIF"           , IMAGE "tiff"                                                                  },
	{ ".XXX"           , APPLICATION "octet-stream"                                                    },
	{ ".Z"             , APPLICATION "x-compress"                                                      },
	{ ".aa"            , AUDIO "x-pn-audibleaudio"                                                     },
	{ ".ac3"           , AUDIO "ac3"                                                                   },
	{ ".acsm"          , APPLICATION "vnd.adobe.adept+xml"                                             },
	{ ".ada"           , TEXT "x-ada"                                                                  },
	{ ".adf"           , MULTIPART "appledouble"                                                       },
	{ ".afa"           , APPLICATION "x-astrotite-afa"                                                 },
	{ ".afm"           , APPLICATION "x-font-adobe-metric"                                             },
	{ ".ai"            , APPLICATION "illustrator"                                                     },
	{ ".aif"           , AUDIO "x-aiff"                                                                },
	{ ".aifc"          , AUDIO "x-aiff"                                                                },
	{ ".aiff"          , AUDIO "x-aiff"                                                                },
	{ ".air"           , APPLICATION "vnd.adobe.air-application-installer-package+zip;version=\"1.0\"" },
	{ ".aj"            , TEXT "x-aspectj"                                                              },
	{ ".amr"           , AUDIO "amr"                                                                   },
	{ ".anim"          , TEXT "x-yaml"                                                                 },
	{ ".anpa"          , TEXT "vnd.iptc.anpa"                                                          },
	{ ".ans"           , TEXT "plain"                                                                  },
	{ ".apl"           , TEXT "apl"                                                                    },
	{ ".apng"          , IMAGE "vnd.mozilla.apng"                                                      },
	{ ".applescript"   , TEXT "x-applescript"                                                          },
	{ ".apr"           , APPLICATION "vnd.lotus-approach;version=\"97\""                               },
	{ ".apt"           , APPLICATION "vnd.lotus-approach"                                              },
	{ ".arc"           , APPLICATION "x-internet-archive;version=\"1.0\""                              },
	{ ".arw"           , IMAGE "x-raw-sony"                                                            },
	{ ".as"            , TEXT "x-actionscript"                                                         },
	{ ".asc"           , TEXT "plain"                                                                  },
	{ ".asciidoc"      , TEXT "x-asciidoc"                                                             },
	{ ".asf"           , APPLICATION "vnd.ms-asf"                                                      },
	{ ".asice"         , APPLICATION "vnd.etsi.asic-e+zip"                                             },
	{ ".asics"         , APPLICATION "vnd.etsi.asic-s+zip"                                             },
	{ ".asn"           , TEXT "x-ttcn-asn"                                                             },
	{ ".asp"           , APPLICATION "x-aspx"                                                          },
	{ ".aspx"          , TEXT "aspdotnet"                                                              },
	{ ".asy"           , TEXT "x-spreadsheet"                                                          },
	{ ".atom"          , APPLICATION "atom+xml"                                                        },
	{ ".au"            , AUDIO "basic"                                                                 },
	{ ".avi"           , VIDEO "msvideo"                                                               },
	{ ".awb"           , AUDIO "amr-wb"                                                                },
	{ ".awk"           , TEXT "x-awk"                                                                  },
	{ ".axc"           , TEXT "plain"                                                                  },
	{ ".axx"           , APPLICATION "x-axcrypt"                                                       },
	{ ".b"             , TEXT "x-brainfuck"                                                            },
	{ ".b6z"           , APPLICATION "x-b6z-compressed"                                                },
	{ ".bas"           , TEXT "x-basic"                                                                },
	{ ".bay"           , IMAGE "x-raw-casio"                                                           },
	{ ".bik"           , VIDEO "vnd.radgamettools.bink"                                                },
	{ ".bik2"          , VIDEO "vnd.radgamettools.bink;version=\"2\""                                  },
	{ ".bin"           , APPLICATION "x-macbinary"                                                     },
	{ ".bmp"           , IMAGE "bmp"                                                                   },
	{ ".bpg"           , IMAGE "x-bpg"                                                                 },
	{ ".bpm"           , APPLICATION "bizagi-modeler"                                                  },
	{ ".bsp"           , MODEL "vnd.valve.source.compiled-map"                                         },
	{ ".btf"           , IMAGE "tiff"                                                                  },
	{ ".bw"            , IMAGE "x-sgi-bw"                                                              },
	{ ".bz2"           , APPLICATION "x-bzip2"                                                         },
	{ ".c"             , TEXT "x-csrc"                                                                 },
	{ ".cab"           , APPLICATION "vnd.ms-cab-compressed"                                           },
	{ ".cabal"         , TEXT "x-haskell"                                                              },
	{ ".cap"           , APPLICATION "vnd.tcpdump.pcap"                                                },
	{ ".catmaterial"   , APPLICATION "octet-stream;version=\"5\""                                      },
	{ ".catpart"       , APPLICATION "octet-stream;version=\"5\""                                      },
	{ ".catproduct"    , APPLICATION "octet-stream;version=\"5\""                                      },
	{ ".cbl"           , TEXT "x-cobol"                                                                },
	{ ".cbor"          , APPLICATION "cbor"                                                            },
	{ ".cbz"           , APPLICATION "x-cbr"                                                           },
	{ ".cca"           , APPLICATION "octet-stream"                                                    },
	{ ".cda"           , APPLICATION "x-cdf"                                                           },
	{ ".cdf"           , APPLICATION "x-netcdf"                                                        },
	{ ".cdx"           , CHEMICAL "x-cdx"                                                              },
	{ ".cfg"           , TEXT "x-config"                                                               },
	{ ".cfm"           , TEXT "x-coldfusion"                                                           },
	{ ".cfs"           , APPLICATION "x-cfs-compressed"                                                },
	{ ".cgi"           , TEXT "x-cgi"                                                                  },
	{ ".cgm"           , IMAGE "cgm"                                                                   },
	{ ".chm"           , APPLICATION "vnd.ms-htmlhelp"                                                 },
	{ ".chrt"          , APPLICATION "x-kchart"                                                        },
	{ ".chs"           , TEXT "x-haskell"                                                              },
	{ ".cif"           , CHEMICAL "x-cif"                                                              },
	{ ".ck"            , TEXT "x-java"                                                                 },
	{ ".cl"            , TEXT "x-common-lisp"                                                          },
	{ ".class"         , APPLICATION "x-java"                                                          },
	{ ".clj"           , TEXT "x-clojure"                                                              },
	{ ".cls"           , TEXT "x-vbasic"                                                               },
	{ ".cmake"         , TEXT "x-cmake"                                                                },
	{ ".cml"           , CHEMICAL "x-cml"                                                              },
	{ ".cob"           , TEXT "x-cobol"                                                                },
	{ ".cod"           , IMAGE "cis-cod"                                                               },
	{ ".coffee"        , APPLICATION "vnd.coffeescript"                                                },
	{ ".cp"            , TEXT "x-pascal"                                                               },
	{ ".cpio"          , APPLICATION "x-cpio"                                                          },
	{ ".cpp"           , TEXT "x-c++src"                                                               },
	{ ".cr"            , TEXT "x-crystal"                                                              },
	{ ".crw"           , IMAGE "x-canon-crw"                                                           },
	{ ".crx"           , APPLICATION "x-chrome-package"                                                },
	{ ".cs"            , TEXT "x-csharp"                                                               },
	{ ".cshtml"        , TEXT "html"                                                                   },
	{ ".cson"          , TEXT "x-coffeescript"                                                         },
	{ ".csr"           , APPLICATION "pkcs10"                                                          },
	{ ".css"           , TEXT "css"                                                                    },
	{ ".csv"           , TEXT "csv"                                                                    },
	{ ".csvs"          , TEXT "csv-schema"                                                             },
	{ ".cu"            , TEXT "x-c++src"                                                               },
	{ ".cur"           , IMAGE "x-win-bitmap"                                                          },
	{ ".cwl"           , TEXT "x-yaml"                                                                 },
	{ ".cy"            , TEXT "javascript"                                                             },
	{ ".d"             , TEXT "x-d"                                                                    },
	{ ".dae"           , TEXT "xml"                                                                    },
	{ ".dart"          , APPLICATION "dart"                                                            },
	{ ".dat"           , APPLICATION "dbase"                                                           },
	{ ".db"            , APPLICATION "x-sqlite3"                                                       },
	{ ".dbf"           , APPLICATION "x-dbf"                                                           },
	{ ".dcm"           , APPLICATION "dicom"                                                           },
	{ ".dcr"           , APPLICATION "x-director"                                                      },
	{ ".dcx"           , IMAGE "x-dcx"                                                                 },
	{ ".deb"           , APPLICATION "vnd.debian.binary-package"                                       },
	{ ".der"           , APPLICATION "x-x509-ca-cert"                                                  },
	{ ".dex"           , APPLICATION "x-dex"                                                           },
	{ ".dgc"           , APPLICATION "x-dgc-compressed"                                                },
	{ ".diff"          , TEXT "x-diff"                                                                 },
	{ ".dir"           , APPLICATION "x-director"                                                      },
	{ ".dita"          , APPLICATION "dita+xml;format=topic"                                           },
	{ ".ditamap"       , APPLICATION "dita+xml;format=map"                                             },
	{ ".ditaval"       , APPLICATION "dita+xml;format=val"                                             },
	{ ".diz"           , TEXT "plain"                                                                  },
	{ ".djv"           , IMAGE "vnd.djvu"                                                              },
	{ ".djvu"          , IMAGE "vnd.djvu"                                                              },
	{ ".dll"           , APPLICATION "octet-stream"                                                    },
	{ ".dls"           , AUDIO "dls"                                                                   },
	{ ".dmg"           , APPLICATION "x-apple-diskimage"                                               },
	{ ".dng"           , IMAGE "x-raw-adobe"                                                           },
	{ ".doc"           , APPLICATION "msword"                                                          },
	{ ".dockerfile"    , TEXT "x-dockerfile"                                                           },
	{ ".docm"          , APPLICATION "vnd.ms-word.document.macroenabled.12"                            },
	{ ".docx"          , APPLICATION "vnd.openxmlformats-officedocument.wordprocessingml.document"     },
	{ ".dot"           , APPLICATION "msword;version=\"97-2003\""                                      },
	{ ".dotm"          , APPLICATION "vnd.ms-word.template.macroenabled.12"                            },
	{ ".dotx"          , APPLICATION "vnd.openxmlformats-officedocument.wordprocessingml.template"     },
	{ ".dpx"           , IMAGE "x-dpx"                                                                 },
	{ ".drc"           , VIDEO "x-dirac"                                                               },
	{ ".druby"         , TEXT "x-ruby"                                                                 },
	{ ".dtd"           , APPLICATION "xml-dtd"                                                         },
	{ ".dts"           , AUDIO "vnd.dts"                                                               },
	{ ".dv"            , VIDEO "dv"                                                                    },
	{ ".dvi"           , APPLICATION "x-dvi"                                                           },
	{ ".dwf"           , APPLICATION "dwf;version=\"6.0\""                                             },
	{ ".dwfx"          , MODEL "vnd.dwfx+xps"                                                          },
	{ ".dwg"           , IMAGE "vnd.dwg"                                                               },
	{ ".dwl"           , APPLICATION "octet-stream"                                                    },
	{ ".dx"            , APPLICATION "dec-dx."                                                         },
	{ ".dxb"           , IMAGE "vnd.dxb"                                                               },
	{ ".dxf"           , IMAGE "vnd.dxf"                                                               },
	{ ".dxr"           , AUDIO "prs.sid;version=\"1\""                                                 },
	{ ".dylan"         , TEXT "x-dylan"                                                                },
	{ ".e"             , TEXT "x-eiffel"                                                               },
	{ ".eb"            , TEXT "x-python"                                                               },
	{ ".ebnf"          , TEXT "x-ebnf"                                                                 },
	{ ".ebuild"        , TEXT "x-sh"                                                                   },
	{ ".ecl"           , TEXT "x-ecl"                                                                  },
	{ ".eclass"        , TEXT "x-sh"                                                                   },
	{ ".ecr"           , TEXT "html"                                                                   },
	{ ".edc"           , APPLICATION "json"                                                            },
	{ ".edn"           , TEXT "x-clojure"                                                              },
	{ ".eex"           , TEXT "html"                                                                   },
	{ ".el"            , TEXT "x-emacs-lisp"                                                           },
	{ ".elc"           , APPLICATION "x-elc"                                                           },
	{ ".elm"           , TEXT "x-elm"                                                                  },
	{ ".em"            , TEXT "x-coffeescript"                                                         },
	{ ".emf"           , IMAGE "emf"                                                                   },
	{ ".eml"           , MESSAGE "rfc822"                                                              },
	{ ".enr"           , APPLICATION "x-endnote-refer"                                                 },
	{ ".ens"           , APPLICATION "x-endnote-style"                                                 },
	{ ".enz"           , APPLICATION "x-endnote-connect"                                               },
	{ ".eot"           , APPLICATION "vnd.ms-fontobject"                                               },
	{ ".epj"           , APPLICATION "json"                                                            },
	{ ".eps"           , APPLICATION "postscript"                                                      },
	{ ".epub"          , APPLICATION "epub+zip"                                                        },
	{ ".eq"            , TEXT "x-csharp"                                                               },
	{ ".erb"           , APPLICATION "x-erb"                                                           },
	{ ".erf"           , IMAGE "x-raw-epson"                                                           },
	{ ".erl"           , TEXT "x-erlang"                                                               },
	{ ".es"            , APPLICATION "ecmascript"                                                      },
	{ ".exe"           , APPLICATION "x-dosexec"                                                       },
	{ ".exp"           , TEXT "x-expect"                                                               },
	{ ".exr"           , IMAGE "x-exr;version=\"2\""                                                   },
	{ ".f"             , TEXT "x-fortran"                                                              },
	{ ".f4a"           , VIDEO "mp4"                                                                   },
	{ ".f4m"           , APPLICATION "f4m"                                                             },
	{ ".f90"           , TEXT "x-fortran"                                                              },
	{ ".factor"        , TEXT "x-factor"                                                               },
	{ ".fb2"           , APPLICATION "x-fictionbook+xml"                                               },
	{ ".fdf"           , APPLICATION "vnd.fdf"                                                         },
	{ ".fff"           , IMAGE "x-raw-imacon"                                                          },
	{ ".fh"            , IMAGE "x-freehand"                                                            },
	{ ".fig"           , APPLICATION "x-matlab-data"                                                   },
	{ ".fits"          , IMAGE "fits"                                                                  },
	{ ".flac"          , AUDIO "flac"                                                                  },
	{ ".flif"          , IMAGE "flif"                                                                  },
	{ ".flv"           , VIDEO "x-flv"                                                                 },
	{ ".fm"            , APPLICATION "vnd.framemaker"                                                  },
	{ ".fmz"           , APPLICATION "octet-stream"                                                    },
	{ ".folio"         , APPLICATION "vnd.adobe.folio+zip"                                             },
	{ ".fp7"           , APPLICATION "x-filemaker"                                                     },
	{ ".fpx"           , IMAGE "vnd.fpx"                                                               },
	{ ".fref"          , TEXT "plain"                                                                  },
	{ ".fs"            , TEXT "x-fsharp"                                                               },
	{ ".fth"           , TEXT "x-forth"                                                                },
	{ ".g3"            , IMAGE "g3fax"                                                                 },
	{ ".gbr"           , APPLICATION "vnd.gerber"                                                      },
	{ ".gca"           , APPLICATION "x-gca-compressed"                                                },
	{ ".geo"           , APPLICATION "vnd.geogebra.file;version=\"1.0\""                               },
	{ ".gf"            , TEXT "x-haskell"                                                              },
	{ ".ggb"           , APPLICATION "vnd.geogebra.file"                                               },
	{ ".gif"           , IMAGE "gif"                                                                   },
	{ ".gitconfig"     , TEXT "x-properties"                                                           },
	{ ".gitignore"     , TEXT "x-sh"                                                                   },
	{ ".glf"           , TEXT "x-tcl"                                                                  },
	{ ".gml"           , APPLICATION "gml+xml"                                                         },
	{ ".gn"            , TEXT "x-python"                                                               },
	{ ".gnumeric"      , APPLICATION "x-gnumeric"                                                      },
	{ ".go"            , TEXT "x-go"                                                                   },
	{ ".grb"           , APPLICATION "x-grib"                                                          },
	{ ".groovy"        , TEXT "x-groovy"                                                               },
	{ ".gsp"           , APPLICATION "x-jsp"                                                           },
	{ ".gtar"          , APPLICATION "x-gtar"                                                          },
	{ ".gz"            , APPLICATION "gzip"                                                            },
	{ ".h"             , TEXT "x-chdr"                                                                 },
	{ ".haml"          , TEXT "x-haml"                                                                 },
	{ ".hcl"           , TEXT "x-ruby"                                                                 },
	{ ".hdf"           , APPLICATION "x-hdf"                                                           },
	{ ".hdp"           , IMAGE "vnd.ms-photo"                                                          },
	{ ".hdr"           , IMAGE "vnd.radiance"                                                          },
	{ ".hh"            , APPLICATION "x-httpd-php"                                                     },
	{ ".hpgl"          , APPLICATION "vnd.hp-hpgl"                                                     },
	{ ".hpp"           , TEXT "x-c++hdr"                                                               },
	{ ".hqx"           , APPLICATION "mac-binhex"                                                      },
	{ ".hs"            , TEXT "x-haskell"                                                              },
	{ ".htm"           , TEXT "html"                                                                   },
	{ ".html"          , TEXT "html"                                                                   },
	{ ".http"          , MESSAGE "http"                                                                },
	{ ".hx"            , TEXT "x-haxe"                                                                 },
	{ ".ibooks"        , APPLICATION "x-ibooks+zip"                                                    },
	{ ".ico"           , IMAGE "vnd.microsoft.icon"                                                    },
	{ ".ics"           , TEXT "calendar"                                                               },
	{ ".idl"           , TEXT "x-idl"                                                                  },
	{ ".idml"          , APPLICATION "vnd.adobe.indesign-idml-package"                                 },
	{ ".iges"          , MODEL "iges;version=\"5.x\""                                                  },
	{ ".igs"           , MODEL "iges"                                                                  },
	{ ".iiq"           , IMAGE "x-raw-phaseone"                                                        },
	{ ".ind"           , APPLICATION "octet-stream;version=\"generic\""                                },
	{ ".indd"          , APPLICATION "x-adobe-indesign"                                                },
	{ ".inf"           , APPLICATION "inf"                                                             },
	{ ".ini"           , TEXT "x-ini"                                                                  },
	{ ".inx"           , APPLICATION "x-adobe-indesign-interchange"                                    },
	{ ".ipa"           , APPLICATION "x-itunes-ipa"                                                    },
	{ ".ipynb"         , APPLICATION "json"                                                            },
	{ ".irclog"        , TEXT "mirc"                                                                   },
	{ ".iso"           , APPLICATION "x-iso9660-image"                                                 },
	{ ".itk"           , APPLICATION "x-tcl"                                                           },
	{ ".j2c"           , IMAGE "x-jp2-codestream"                                                      },
	{ ".jade"          , TEXT "x-pug"                                                                  },
	{ ".jar"           , APPLICATION "java-archive"                                                    },
	{ ".java"          , TEXT "x-java"                                                                 },
	{ ".jinja"         , TEXT "x-django"                                                               },
	{ ".jl"            , TEXT "x-julia"                                                                },
	{ ".jls"           , IMAGE "jls"                                                                   },
	{ ".jng"           , IMAGE "x-jng"                                                                 },
	{ ".jnilib"        , APPLICATION "x-java-jnilib"                                                   },
	{ ".jp2"           , IMAGE "jpx"                                                                   },
	{ ".jpe"           , IMAGE "jpeg"                                                                  },
	{ ".jpf"           , IMAGE "jpx"                                                                   },
	{ ".jpg"           , IMAGE "jpeg"                                                                  },
	{ ".jpm"           , IMAGE "jpm"                                                                   },
	{ ".jq"            , APPLICATION "json"                                                            },
	{ ".js"            , APPLICATION "javascript"                                                      },
	{ ".json"          , APPLICATION "json"                                                            },
	{ ".json-patch"    , APPLICATION "json-patch+json"                                                 },
	{ ".json5"         , APPLICATION "json"                                                            },
	{ ".jsonld"        , APPLICATION "ld+json"                                                         },
	{ ".jsp"           , APPLICATION "x-jsp"                                                           },
	{ ".jsx"           , TEXT "jsx"                                                                    },
	{ ".jxr"           , IMAGE "jxr"                                                                   },
	{ ".k25"           , IMAGE "x-raw-kodak"                                                           },
	{ ".kicad_pcb"     , TEXT "x-common-lisp"                                                          },
	{ ".kid"           , TEXT "xml"                                                                    },
	{ ".kil"           , APPLICATION "x-killustrator"                                                  },
	{ ".kit"           , TEXT "html"                                                                   },
	{ ".kml"           , APPLICATION "vnd.google-earth.kml+xml"                                        },
	{ ".kmz"           , APPLICATION "vnd.google-earth.kmz"                                            },
	{ ".kpr"           , APPLICATION "x-kpresenter"                                                    },
	{ ".kra"           , APPLICATION "x-krita"                                                         },
	{ ".ksp"           , APPLICATION "x-kspread"                                                       },
	{ ".kt"            , TEXT "x-kotlin"                                                               },
	{ ".ktx"           , IMAGE "ktx"                                                                   },
	{ ".kwd"           , APPLICATION "x-kword"                                                         },
	{ ".l"             , TEXT "x-lex"                                                                  },
	{ ".latex"         , APPLICATION "x-latex"                                                         },
	{ ".latte"         , TEXT "x-smarty"                                                               },
	{ ".less"          , TEXT "x-less"                                                                 },
	{ ".lfe"           , TEXT "x-common-lisp"                                                          },
	{ ".lha"           , APPLICATION "x-lzh-compressed"                                                },
	{ ".lhs"           , TEXT "x-literate-haskell"                                                     },
	{ ".lisp"          , TEXT "x-common-lisp"                                                          },
	{ ".log"           , TEXT "x-log"                                                                  },
	{ ".lookml"        , TEXT "x-yaml"                                                                 },
	{ ".ls"            , TEXT "x-livescript"                                                           },
	{ ".lua"           , TEXT "x-lua"                                                                  },
	{ ".lvproj"        , TEXT "xml"                                                                    },
	{ ".lwp"           , APPLICATION "vnd.lotus-wordpro"                                               },
	{ ".lz"            , APPLICATION "x-lzip"                                                          },
	{ ".lzma"          , APPLICATION "x-lzma"                                                          },
	{ ".m"             , TEXT "x-objcsrc"                                                              },
	{ ".m3"            , TEXT "x-modula"                                                               },
	{ ".m3u"           , AUDIO "x-mpegurl"                                                             },
	{ ".maff"          , APPLICATION "x-maff"                                                          },
	{ ".mak"           , TEXT "x-cmake"                                                                },
	{ ".marko"         , TEXT "html"                                                                   },
	{ ".mas"           , APPLICATION "vnd.lotus-freelance"                                             },
	{ ".mat"           , APPLICATION "matlab-mat"                                                      },
	{ ".mathematica"   , TEXT "x-mathematica"                                                          },
	{ ".matlab"        , TEXT "x-octave"                                                               },
	{ ".maxpat"        , APPLICATION "json"                                                            },
	{ ".mbox"          , APPLICATION "mbox"                                                            },
	{ ".mbx"           , APPLICATION "mbox"                                                            },
	{ ".mcw"           , APPLICATION "msword;version=\"5.0\""                                          },
	{ ".md"            , TEXT "markdown"                                                               },
	{ ".mdi"           , IMAGE "vnd.ms-modi"                                                           },
	{ ".mef"           , IMAGE "x-raw-mamiya"                                                          },
	{ ".metal"         , TEXT "x-c++src"                                                               },
	{ ".mht"           , MULTIPART "multipart/related"                                                           },
	{ ".mid"           , AUDIO "midi"                                                                  },
	{ ".mif"           , APPLICATION "x-mif"                                                           },
	{ ".mix"           , IMAGE "vnd.mix"                                                               },
	{ ".mj2"           , VIDEO "mj2"                                                                   },
	{ ".mkv"           , VIDEO "x-matroska"                                                            },
	{ ".ml"            , TEXT "x-ocaml"                                                                },
	{ ".mlp"           , AUDIO "vnd.dolby.mlp"                                                         },
	{ ".mm"            , APPLICATION "x-freemind"                                                      },
	{ ".mmp"           , APPLICATION "vnd.mindjet.mindmanager"                                         },
	{ ".mmr"           , IMAGE "vnd.fujixerox.edmics-mmr"                                              },
	{ ".mng"           , VIDEO "x-mng"                                                                 },
	{ ".mo"            , TEXT "x-modelica"                                                             },
	{ ".mobi"          , APPLICATION "x-mobipocket-ebook"                                              },
	{ ".mod"           , APPLICATION "octet-stream;version=\"4\""                                      },
	{ ".mol"           , CHEMICAL "x-mdl-molfile"                                                      },
	{ ".mos"           , IMAGE "x-raw-leaf"                                                            },
	{ ".mov"           , VIDEO "quicktime"                                                             },
	{ ".mp1"           , AUDIO "mpeg"                                                                  },
	{ ".mp2"           , AUDIO "mpeg"                                                                  },
	{ ".mp3"           , AUDIO "mpeg"                                                                  },
	{ ".mp4"           , VIDEO "mp4"                                                                   },
	{ ".mpeg"          , VIDEO "mpeg"                                                                  },
	{ ".mpg"           , VIDEO "mpeg"                                                                  },
	{ ".mpga"          , AUDIO "mpeg"                                                                  },
	{ ".mpp"           , APPLICATION "vnd.ms-project;version=\"2010\""                                 },
	{ ".mpx"           , APPLICATION "x-project;version=\"4.0\""                                       },
	{ ".mrc"           , APPLICATION "marc"                                                            },
	{ ".mrw"           , IMAGE "x-raw-minolta"                                                         },
	{ ".msg"           , APPLICATION "vnd.ms-outlook"                                                  },
	{ ".msi"           , APPLICATION "x-msi"                                                           },
	{ ".mso"           , APPLICATION "x-mso"                                                           },
	{ ".mtml"          , TEXT "html"                                                                   },
	{ ".muf"           , TEXT "x-forth"                                                                },
	{ ".mumps"         , TEXT "x-mumps"                                                                },
	{ ".mxf"           , APPLICATION "mxf"                                                             },
	{ ".mxl"           , APPLICATION "vnd.recordare.musicxml"                                          },
	{ ".mxmf"          , AUDIO "mobile-xmf"                                                            },
	{ ".n3"            , TEXT "n3"                                                                     },
	{ ".nap"           , IMAGE "naplps"                                                                },
	{ ".nb"            , APPLICATION "mathematica"                                                     },
	{ ".nc"            , APPLICATION "x-netcdf"                                                        },
	{ ".nef"           , IMAGE "x-raw-nikon"                                                           },
	{ ".nfo"           , TEXT "x-nfo"                                                                  },
	{ ".nginxconf"     , TEXT "x-nginx-conf"                                                           },
	{ ".nif"           , APPLICATION "vnd.music-niff"                                                  },
	{ ".nl"            , TEXT "x-common-lisp"                                                          },
	{ ".nlogo"         , TEXT "x-common-lisp"                                                          },
	{ ".ns2"           , APPLICATION "vnd.lotus-notes;version=\"2\""                                   },
	{ ".ns3"           , APPLICATION "vnd.lotus-notes;version=\"3\""                                   },
	{ ".ns4"           , APPLICATION "vnd.lotus-notes;version=\"4\""                                   },
	{ ".nsf"           , APPLICATION "vnd.lotus-notes"                                                 },
	{ ".nsi"           , TEXT "x-nsis"                                                                 },
	{ ".ntf"           , APPLICATION "vnd.nitf"                                                        },
	{ ".nu"            , TEXT "x-scheme"                                                               },
	{ ".numpy"         , TEXT "x-python"                                                               },
	{ ".nut"           , TEXT "x-c++src"                                                               },
	{ ".ocaml"         , TEXT "x-ocaml"                                                                },
	{ ".odb"           , APPLICATION "vnd.oasis.opendocument.database"                                 },
	{ ".odc"           , APPLICATION "vnd.oasis.opendocument.chart"                                    },
	{ ".odf"           , APPLICATION "vnd.oasis.opendocument.formula"                                  },
	{ ".odft"          , APPLICATION "vnd.oasis.opendocument.formula-template"                         },
	{ ".odg"           , APPLICATION "vnd.oasis.opendocument.graphics"                                 },
	{ ".odi"           , APPLICATION "vnd.oasis.opendocument.image"                                    },
	{ ".odm"           , APPLICATION "vnd.oasis.opendocument.text-master"                              },
	{ ".odp"           , APPLICATION "vnd.oasis.opendocument.presentation"                             },
	{ ".ods"           , APPLICATION "vnd.oasis.opendocument.spreadsheet"                              },
	{ ".odt"           , APPLICATION "vnd.oasis.opendocument.text"                                     },
	{ ".ofx"           , APPLICATION "x-ofx;version=\"2.1.1\""                                         },
	{ ".oga"           , AUDIO "ogg"                                                                   },
	{ ".ogg"           , AUDIO "ogg"                                                                   },
	{ ".ogm"           , VIDEO "x-ogm"                                                                 },
	{ ".ogv"           , VIDEO "ogg"                                                                   },
	{ ".ogx"           , APPLICATION "ogg"                                                             },
	{ ".one"           , APPLICATION "msonenote"                                                       },
	{ ".opf"           , APPLICATION "x-dtbook+xml"                                                    },
	{ ".opus"          , AUDIO "opus"                                                                  },
	{ ".ora"           , IMAGE "openraster"                                                            },
	{ ".orf"           , IMAGE "x-raw-olympus"                                                         },
	{ ".otc"           , APPLICATION "vnd.oasis.opendocument.chart-template"                           },
	{ ".otf"           , APPLICATION "x-font-otf"                                                      },
	{ ".otg"           , APPLICATION "vnd.oasis.opendocument.graphics-template"                        },
	{ ".oth"           , APPLICATION "vnd.oasis.opendocument.text-web"                                 },
	{ ".oti"           , APPLICATION "vnd.oasis.opendocument.image-template"                           },
	{ ".otm"           , APPLICATION "vnd.oasis.opendocument.text-master"                              },
	{ ".otp"           , APPLICATION "vnd.oasis.opendocument.presentation-template"                    },
	{ ".ots"           , APPLICATION "vnd.oasis.opendocument.spreadsheet-template"                     },
	{ ".ott"           , APPLICATION "vnd.oasis.opendocument.text-template"                            },
	{ ".ova"           , APPLICATION "x-ova"                                                           },
	{ ".oxps"          , APPLICATION "oxps"                                                            },
	{ ".oz"            , TEXT "x-oz"                                                                   },
	{ ".p"             , TEXT "x-pascal"                                                               },
	{ ".p65"           , APPLICATION "vnd.pagemaker"                                                   },
	{ ".pab"           , APPLICATION "vnd.ms-outlook"                                                  },
	{ ".pack"          , APPLICATION "package"                                                         },
	{ ".pam"           , IMAGE "x-portable-arbitrarymap"                                               },
	{ ".pas"           , TEXT "x-pascal"                                                               },
	{ ".pbm"           , IMAGE "x-portable-bitmap"                                                     },
	{ ".pcap"          , APPLICATION "vnd.tcpdump.pcap"                                                },
	{ ".pcapng"        , APPLICATION "vnd.tcpdump.pcap"                                                },
	{ ".pcl"           , APPLICATION "vnd.hp-pcl"                                                      },
	{ ".pct"           , IMAGE "x-pict;version=\"2.0\""                                                },
	{ ".pcx"           , IMAGE "vnd.zbrush.pcx"                                                        },
	{ ".pdb"           , APPLICATION "vnd.palm"                                                        },
	{ ".pdf"           , APPLICATION "pdf"                                                             },
	{ ".pfm"           , APPLICATION "x-font-printer-metric"                                           },
	{ ".pfr"           , APPLICATION "font-tdpfr"                                                      },
	{ ".pgm"           , IMAGE "x-portable-graymap"                                                    },
	{ ".pgn"           , APPLICATION "x-chess-pgn"                                                     },
	{ ".pgsql"         , TEXT "x-sql"                                                                  },
	{ ".php"           , TEXT "x-php"                                                                  },
	{ ".phtml"         , APPLICATION "x-httpd-php"                                                     },
	{ ".pic"           , IMAGE "x-pict"                                                                },
	{ ".pict"          , IMAGE "x-pict"                                                                },
	{ ".pkpass"        , APPLICATION "vnd.apple.pkpass"                                                },
	{ ".pl"            , TEXT "x-perl"                                                                 },
	{ ".pls"           , TEXT "x-plsql"                                                                },
	{ ".png"           , IMAGE "png"                                                                   },
	{ ".pnm"           , IMAGE "x-portable-anymap"                                                     },
	{ ".pod"           , TEXT "x-perl"                                                                 },
	{ ".por"           , APPLICATION "x-spss-por"                                                      },
	{ ".potm"          , APPLICATION "vnd.ms-powerpoint.template.macroenabled.12;version=\"2007\""     },
	{ ".potx"          , APPLICATION "vnd.openxmlformats-officedocument.presentationml.template"       },
	{ ".pp"            , TEXT "x-puppet"                                                               },
	{ ".ppam"          , APPLICATION "vnd.ms-powerpoint.addin.macroenabled.12"                         },
	{ ".ppm"           , IMAGE "x-portable-pixmap"                                                     },
	{ ".pps"           , APPLICATION "vnd.ms-powerpoint;version=\"97-2003\""                           },
	{ ".ppsm"          , APPLICATION "vnd.ms-powerpoint.slideshow.macroenabled.12"                     },
	{ ".ppsx"          , APPLICATION "vnd.openxmlformats-officedocument.presentationml.slideshow"      },
	{ ".ppt"           , APPLICATION "vnd.ms-powerpoint"                                               },
	{ ".pptm"          , APPLICATION "vnd.ms-powerpoint.presentation.macroenabled.12"                  },
	{ ".pptx"          , APPLICATION "vnd.openxmlformats-officedocument.presentationml.presentation"   },
	{ ".prc"           , APPLICATION "vnd.palm"                                                        },
	{ ".pro"           , TEXT "x-prolog"                                                               },
	{ ".project"       , APPLICATION "octet-stream;version=\"4\""                                      },
	{ ".properties"    , TEXT "properties"                                                             },
	{ ".proto"         , TEXT "x-protobuf"                                                             },
	{ ".ps"            , APPLICATION "postscript"                                                      },
	{ ".ps1"           , APPLICATION "x-powershell"                                                    },
	{ ".psb"           , IMAGE "vnd.adobe.photoshop"                                                   },
	{ ".psd"           , IMAGE "vnd.adobe.photoshop"                                                   },
	{ ".psid"          , AUDIO "prs.sid;version=\"2\""                                                 },
	{ ".pst"           , APPLICATION "vnd.ms-outlook-pst"                                              },
	{ ".ptx"           , IMAGE "x-raw-pentax"                                                          },
	{ ".purs"          , TEXT "x-haskell"                                                              },
	{ ".pxn"           , IMAGE "x-raw-logitech"                                                        },
	{ ".py"            , TEXT "x-python"                                                               },
	{ ".pyx"           , TEXT "x-cython"                                                               },
	{ ".qcd"           , APPLICATION "vnd.quark.quarkxpress"                                           },
	{ ".qcp"           , AUDIO "qcelp"                                                                 },
	{ ".qif"           , APPLICATION "qif"                                                             },
	{ ".qxp"           , APPLICATION "vnd.quark.quarkxpress"                                           },
	{ ".qxp report"    , APPLICATION "vnd.quark.quarkxpress"                                           },
	{ ".r"             , TEXT "x-rsrc"                                                                 },
	{ ".r3d"           , IMAGE "x-raw-red"                                                             },
	{ ".ra"            , AUDIO "vnd.rn-realaudio"                                                      },
	{ ".raf"           , IMAGE "x-raw-fuji"                                                            },
	{ ".ram"           , AUDIO "vnd.rn-realaudio"                                                      },
	{ ".raml"          , TEXT "x-yaml"                                                                 },
	{ ".rar"           , APPLICATION "vnd.rar"                                                         },
	{ ".rar"           , APPLICATION "vnd.rar"                                                         },
	{ ".ras"           , IMAGE "x-sun-raster"                                                          },
	{ ".raw"           , IMAGE "x-raw-panasonic"                                                       },
	{ ".rb"            , TEXT "x-ruby"                                                                 },
	{ ".rdf"           , APPLICATION "rdf+xml"                                                         },
	{ ".re"            , TEXT "x-rustsrc"                                                              },
	{ ".reg"           , TEXT "x-properties"                                                           },
	{ ".rest"          , TEXT "x-rst"                                                                  },
	{ ".rexx"          , TEXT "x-rexx"                                                                 },
	{ ".rf64"          , AUDIO "x-wav;version=\"0waveformatextensibleencoding\""                       },
	{ ".rfa"           , APPLICATION "octet-stream"                                                    },
	{ ".rft"           , APPLICATION "octet-stream"                                                    },
	{ ".rg"            , TEXT "x-clojure"                                                              },
	{ ".rgb"           , IMAGE "x-rgb"                                                                 },
	{ ".rhtml"         , APPLICATION "x-erb"                                                           },
	{ ".rlc"           , IMAGE "vnd.fujixerox.edmics-rlc"                                              },
	{ ".rm"            , APPLICATION "vnd.rn-realmedia"                                                },
	{ ".rmd"           , TEXT "x-gfm"                                                                  },
	{ ".rmi"           , AUDIO "mid"                                                                   },
	{ ".rmp"           , AUDIO "x-pn-realaudio-plugin"                                                 },
	{ ".roff"          , TEXT "troff"                                                                  },
	{ ".rpm"           , APPLICATION "x-rpm"                                                           },
	{ ".rs"            , TEXT "x-rustsrc"                                                              },
	{ ".rss"           , APPLICATION "rss+xml"                                                         },
	{ ".rst"           , TEXT "x-rst"                                                                  },
	{ ".rte"           , APPLICATION "octet-stream"                                                    },
	{ ".rtf"           , APPLICATION "rtf"                                                             },
	{ ".rv"            , VIDEO "vnd.rn-realvideo"                                                      },
	{ ".rvg"           , APPLICATION "octet-stream"                                                    },
	{ ".rvt"           , APPLICATION "octet-stream"                                                    },
	{ ".rws"           , APPLICATION "octet-stream"                                                    },
	{ ".rwz"           , IMAGE "x-raw-rawzor"                                                          },
	{ ".s"             , TEXT "x-asm"                                                                  },
	{ ".s7m"           , APPLICATION "x-sas-dmdb"                                                      },
	{ ".sa7"           , APPLICATION "x-sas-access"                                                    },
	{ ".sage"          , TEXT "x-python"                                                               },
	{ ".sam"           , APPLICATION "vnd.lotus-wordpro"                                               },
	{ ".sas"           , APPLICATION "x-sas"                                                           },
	{ ".sas7bbak"      , APPLICATION "x-sas-backup"                                                    },
	{ ".sass"          , TEXT "x-sass"                                                                 },
	{ ".sav"           , APPLICATION "x-spss-sav"                                                      },
	{ ".sc7"           , APPLICATION "x-sas-catalog"                                                   },
	{ ".scala"         , TEXT "x-scala"                                                                },
	{ ".sch"           , TEXT "xml"                                                                    },
	{ ".scm"           , TEXT "x-scheme"                                                               },
	{ ".scores"        , TEXT "plain"                                                                  },
	{ ".scss"          , TEXT "x-scss"                                                                 },
	{ ".sd7"           , APPLICATION "x-sas-data"                                                      },
	{ ".sda"           , APPLICATION "vnd.stardivision.draw"                                           },
	{ ".sdc"           , APPLICATION "vnd.stardivision.calc"                                           },
	{ ".sdn"           , TEXT "plain"                                                                  },
	{ ".sdw"           , APPLICATION "vnd.stardivision.writer"                                         },
	{ ".sed"           , TEXT "x-sed"                                                                  },
	{ ".sf7"           , APPLICATION "x-sas-fdb"                                                       },
	{ ".sfd"           , APPLICATION "vnd.font-fontforge-sfd"                                          },
	{ ".sgm"           , TEXT "sgml"                                                                   },
	{ ".sgml"          , TEXT "sgml"                                                                   },
	{ ".sh"            , APPLICATION "x-sh"                                                            },
	{ ".sh-session"    , TEXT "x-sh"                                                                   },
	{ ".shar"          , APPLICATION "x-shar"                                                          },
	{ ".shtml"         , TEXT "x-server-parsed-html"                                                   },
	{ ".si7"           , APPLICATION "x-sas-data-index"                                                },
	{ ".sid"           , AUDIO "prs.sid"                                                               },
	{ ".sit"           , APPLICATION "x-stuffit"                                                       },
	{ ".sitx"          , APPLICATION "x-stuffitx"                                                      },
	{ ".skb"           , APPLICATION "octet-stream"                                                    },
	{ ".skp"           , APPLICATION "vnd.koan"                                                        },
	{ ".sla"           , APPLICATION "vnd.scribus"                                                     },
	{ ".sld"           , APPLICATION "sld"                                                             },
	{ ".sldm"          , APPLICATION "vnd.ms-powerpoint.slide.macroenabled.12;version=\"2007\""        },
	{ ".sldprt"        , APPLICATION "sldworks"                                                        },
	{ ".slim"          , TEXT "x-slim"                                                                 },
	{ ".sls"           , TEXT "x-yaml"                                                                 },
	{ ".sm7"           , APPLICATION "x-sas-mddb"                                                      },
	{ ".smi"           , APPLICATION "smil+xml"                                                        },
	{ ".smk"           , VIDEO "vnd.radgamettools.smacker"                                             },
	{ ".soy"           , TEXT "x-soy"                                                                  },
	{ ".sp7"           , APPLICATION "x-sas-putility"                                                  },
	{ ".sparql"        , APPLICATION "sparql-query"                                                    },
	{ ".spec"          , TEXT "x-rpm-spec"                                                             },
	{ ".spl"           , APPLICATION "x-futuresplash"                                                  },
	{ ".spx"           , AUDIO "speex"                                                                 },
	{ ".sql"           , TEXT "x-sql"                                                                  },
	{ ".sr7"           , APPLICATION "x-sas-itemstor"                                                  },
	{ ".srl"           , APPLICATION "sereal"                                                          },
	{ ".srt"           , TEXT "x-common-lisp"                                                          },
	{ ".ss7"           , APPLICATION "x-sas-program-data"                                              },
	{ ".ssml"          , APPLICATION "ssml+xml"                                                        },
	{ ".st"            , TEXT "x-stsrc"                                                                },
	{ ".st7"           , APPLICATION "x-sas-audit"                                                     },
	{ ".stw"           , APPLICATION "vnd.sun.xml.writer.template"                                     },
	{ ".stx"           , APPLICATION "x-sas-transport"                                                 },
	{ ".su7"           , APPLICATION "x-sas-utility"                                                   },
	{ ".sublime-build" , TEXT "javascript"                                                             },
	{ ".sv"            , TEXT "x-systemverilog"                                                        },
	{ ".sv7"           , APPLICATION "x-sas-view"                                                      },
	{ ".svf"           , IMAGE "vnd.svf"                                                               },
	{ ".svg"           , IMAGE "svg+xml"                                                               },
	{ ".svgz"          , IMAGE "svg+xml"                                                               },
	{ ".swf"           , APPLICATION "vnd.adobe.flash-movie"                                           },
	{ ".swift"         , TEXT "x-swift"                                                                },
	{ ".sxc"           , APPLICATION "vnd.sun.xml.calc;version=\"1.0\""                                },
	{ ".sxd"           , APPLICATION "vnd.sun.xml.draw"                                                },
	{ ".sxi"           , APPLICATION "vnd.sun.xml.impress"                                             },
	{ ".sxw"           , APPLICATION "vnd.sun.xml.writer"                                              },
	{ ".sz"            , APPLICATION "x-snappy-framed"                                                 },
	{ ".t"             , APPLICATION "x-tads"                                                          },
	{ ".tap"           , IMAGE "vnd.tencent.tap"                                                       },
	{ ".tar"           , APPLICATION "x-tar"                                                           },
	{ ".tcl"           , TEXT "x-tcl"                                                                  },
	{ ".tcsh"          , TEXT "x-sh"                                                                   },
	{ ".tex"           , TEXT "x-tex"                                                                  },
	{ ".textile"       , TEXT "x-textile"                                                              },
	{ ".tfw"           , TEXT "plain"                                                                  },
	{ ".tfx"           , IMAGE "tiff"                                                                  },
	{ ".thmx"          , APPLICATION "vnd.ms-officetheme"                                              },
	{ ".tif"           , IMAGE "tiff"                                                                  },
	{ ".tif "          , IMAGE "tiff"                                                                  },
	{ ".tiff"          , IMAGE "tiff"                                                                  },
	{ ".toml"          , TEXT "x-toml"                                                                 },
	{ ".torrent"       , APPLICATION "x-bittorrent"                                                    },
	{ ".tpl"           , TEXT "x-smarty"                                                               },
	{ ".ts"            , APPLICATION "typescript"                                                      },
	{ ".tsv"           , TEXT "tab-separated-values"                                                   },
	{ ".tta"           , AUDIO "tta;version=\"1\""                                                     },
	{ ".ttf"           , APPLICATION "x-font-ttf"                                                      },
	{ ".ttl"           , TEXT "turtle"                                                                 },
	{ ".twig"          , TEXT "x-twig"                                                                 },
	{ ".txt"           , TEXT "plain"                                                                  },
	{ ".u3d"           , MODEL "u3d"                                                                   },
	{ ".uc"            , TEXT "x-java"                                                                 },
	{ ".ulx"           , APPLICATION "x-glulx"                                                         },
	{ ".uno"           , TEXT "x-csharp"                                                               },
	{ ".upc"           , TEXT "x-csrc"                                                                 },
	{ ".url"           , APPLICATION "x-url"                                                           },
	{ ".v"             , TEXT "x-verilog"                                                              },
	{ ".vb"            , TEXT "x-vb"                                                                   },
	{ ".vbs"           , TEXT "x-vbscript"                                                             },
	{ ".vcd"           , APPLICATION "x-cdlink"                                                        },
	{ ".vcf"           , TEXT "vcard"                                                                  },
	{ ".vcs"           , TEXT "x-vcalendar"                                                            },
	{ ".vdx"           , APPLICATION "vnd.visio;version=\"2003-2010\""                                 },
	{ ".vhd"           , TEXT "x-vhdl"                                                                 },
	{ ".vhdl"          , TEXT "x-vhdl"                                                                 },
	{ ".viv"           , VIDEO "vnd-vivo"                                                              },
	{ ".vmdk"          , APPLICATION "x-vmdk"                                                          },
	{ ".vmt"           , APPLICATION "vnd.valve.source.material"                                       },
	{ ".volt"          , TEXT "x-d"                                                                    },
	{ ".vot"           , APPLICATION "x-votable+xml"                                                   },
	{ ".vpb"           , IMAGE "vpb"                                                                   },
	{ ".vsd"           , APPLICATION "vnd.visio"                                                       },
	{ ".vsdm"          , APPLICATION "vnd.ms-visio.drawing.macroenabled.12"                            },
	{ ".vsdx"          , APPLICATION "vnd.visio"                                                       },
	{ ".vssm"          , APPLICATION "vnd.ms-visio.stencil.macroenabled.12"                            },
	{ ".vssx"          , APPLICATION "vnd.ms-visio.stencil"                                            },
	{ ".vstm"          , APPLICATION "vnd.ms-visio.template.macroenabled.12"                           },
	{ ".vstx"          , APPLICATION "vnd.ms-visio.template"                                           },
	{ ".vtf"           , IMAGE "vnd.valve.source.texture"                                              },
	{ ".vtt"           , TEXT "vtt"                                                                    },
	{ ".vwx"           , APPLICATION "vnd.vectorworks;version=\"2015\""                                },
	{ ".w50"           , APPLICATION "vnd.wordperfect;version=\"5.0\""                                 },
	{ ".w51"           , APPLICATION "vnd.wordperfect;version=\"5.1\""                                 },
	{ ".w52"           , APPLICATION "vnd.wordperfect;version=\"5.2\""                                 },
	{ ".warc"          , APPLICATION "warc"                                                            },
	{ ".wast"          , TEXT "x-common-lisp"                                                          },
	{ ".wav"           , AUDIO "x-wav"                                                                 },
	{ ".wbmp"          , IMAGE "vnd.wap.wbmp"                                                          },
	{ ".webapp"        , APPLICATION "x-web-app-manifest+json"                                         },
	{ ".webidl"        , TEXT "x-webidl"                                                               },
	{ ".webm"          , VIDEO "webm"                                                                  },
	{ ".webp"          , IMAGE "webp"                                                                  },
	{ ".wisp"          , TEXT "x-clojure"                                                              },
	{ ".wk1"           , APPLICATION "vnd.lotus-1-2-3;version=\"2.0\""                                 },
	{ ".wk3"           , APPLICATION "vnd.lotus-1-2-3;version=\"3.0\""                                 },
	{ ".wk4"           , APPLICATION "vnd.lotus-1-2-3;version=\"4-5\""                                 },
	{ ".wks"           , APPLICATION "vnd.lotus-1-2-3"                                                 },
	{ ".wma"           , AUDIO "x-ms-wma"                                                              },
	{ ".wmf"           , IMAGE "wmf"                                                                   },
	{ ".wmlc"          , APPLICATION "vnd.wap.wmlc"                                                    },
	{ ".wmls"          , TEXT "vnd.wap.wmlscript"                                                      },
	{ ".wmlsc"         , APPLICATION "vnd.wap.wmlscriptc"                                              },
	{ ".wmv"           , VIDEO "x-ms-wmv"                                                              },
	{ ".woff"          , APPLICATION "font-woff"                                                       },
	{ ".wp4"           , APPLICATION "vnd.wordperfect;version=\"4.0/4.1/4.2\""                         },
	{ ".wpd"           , APPLICATION "vnd.wordperfect"                                                 },
	{ ".wpl"           , APPLICATION "vnd.ms-wpl"                                                      },
	{ ".wrl"           , MODEL "vrml"                                                                  },
	{ ".wsz"           , INTERFACE "x-winamp-skin"                                                     },
	{ ".x3d"           , MODEL "x3d+xml"                                                               },
	{ ".x3f"           , IMAGE "x-raw-sigma"                                                           },
	{ ".xap"           , APPLICATION "x-silverlight-app"                                               },
	{ ".xar"           , APPLICATION "vnd.xara"                                                        },
	{ ".xbm"           , IMAGE "x-xbitmap"                                                             },
	{ ".xc"            , TEXT "x-csrc"                                                                 },
	{ ".xcf"           , IMAGE "xcf"                                                                   },
	{ ".xdm"           , IMAGE "x-xwindowdump;version=\"x10\""                                         },
	{ ".xfdf"          , APPLICATION "vnd.adobe.xfdf"                                                  },
	{ ".xhtml"         , APPLICATION "xhtml+xml"                                                       },
	{ ".xif"           , IMAGE "vnd.xiff"                                                              },
	{ ".xla"           , APPLICATION "vnd.ms-excel;version=\"4.0\""                                    },
	{ ".xlam"          , APPLICATION "vnd.ms-excel.addin.macroenabled.12"                              },
	{ ".xlc"           , APPLICATION "vnd.ms-excel;version=\"3.0\""                                    },
	{ ".xlm"           , APPLICATION "vnd.ms-excel;version=\"3.0\""                                    },
	{ ".xls"           , APPLICATION "vnd.ms-excel"                                                    },
	{ ".xlsb"          , APPLICATION "vnd.ms-excel.sheet.binary.macroenabled.12"                       },
	{ ".xlsm"          , APPLICATION "vnd.ms-excel.sheet.macroenabled.12"                              },
	{ ".xlsx"          , APPLICATION "vnd.openxmlformats-officedocument.spreadsheetml.sheet"           },
	{ ".xltm"          , APPLICATION "vnd.ms-excel.template.macroenabled.12"                           },
	{ ".xltx"          , APPLICATION "vnd.openxmlformats-officedocument.spreadsheetml.template"        },
	{ ".xlw"           , APPLICATION "vnd.ms-excel;version=\"4w\""                                     },
	{ ".xm"            , AUDIO "xm"                                                                    },
	{ ".xmf"           , AUDIO "mobile-xmf"                                                            },
	{ ".xmind"         , APPLICATION "x-xmind"                                                         },
	{ ".xml"           , APPLICATION "xml"                                                             },
	{ ".xmt"           , APPLICATION "mpeg4-iod-xmt"                                                   },
	{ ".xpi"           , APPLICATION "x-xpinstall"                                                     },
	{ ".xpl"           , TEXT "xml"                                                                    },
	{ ".xpm"           , IMAGE "x-xpixmap;version=\"x10\""                                             },
	{ ".xps"           , APPLICATION "oxps"                                                            },
	{ ".xpt"           , APPLICATION "x-sas-xport"                                                     },
	{ ".xq"            , APPLICATION "xquery"                                                          },
	{ ".xquery"        , APPLICATION "xquery"                                                          },
	{ ".xs"            , TEXT "x-csrc"                                                                 },
	{ ".xsd"           , APPLICATION "xml"                                                             },
	{ ".xsl"           , APPLICATION "xml"                                                             },
	{ ".xslfo"         , APPLICATION "xslfo+xml"                                                       },
	{ ".xslt"          , APPLICATION "xslt+xml"                                                        },
	{ ".xsp-config"    , TEXT "xml"                                                                    },
	{ ".xspf"          , APPLICATION "xspf+xml"                                                        },
	{ ".xwd"           , IMAGE "x-xwindowdump"                                                         },
	{ ".xz"            , APPLICATION "x-xz"                                                            },
	{ ".y"             , TEXT "x-yacc"                                                                 },
	{ ".yaml"          , TEXT "x-yaml"                                                                 },
	{ ".yml"           , TEXT "x-yaml"                                                                 },
	{ ".zip"           , APPLICATION "zip"                                                             }
};

static const char *g_signatures_list[] =
{
	"\x05" "\x00\x01\x00\x00\x00"                           , APPLICATION "x-font-ttf"             ,
	"\x0C" "\x04%!PS-Adobe-"                                , APPLICATION "postscript"             ,
	"\x0D" "\x1B%-12345X%!PS"                               , APPLICATION "postscript"             ,
	"\x02" "\x1F\x8B"                                       , APPLICATION "gzip"/*x-gzip*/         ,
	"\x02" "\x1F\x9D"                                       , APPLICATION "x-compress"             ,
	"\x0E" "!<arch>""\x0A""debian"                          , APPLICATION "x-debian-package"       ,
	"\x08" "#! rnews"                                       , MESSAGE "rfc822"                     ,
	"\x0A" "#!/bin/ash"                                     , APPLICATION "x-shellscript"          ,
	"\x0B" "#!/bin/bash"                                    , APPLICATION "x-shellscript"          ,
	"\x0B" "#!/bin/perl"                                    , TEXT "x-perl"                        ,
	"\x09" "#!/bin/sh"                                      , APPLICATION "x-shellscript"          ,
	"\x12" "#!/usr/bin/env lua"                             , TEXT "x-lua"                         ,
	"\x0F" "#!/usr/bin/perl"                                , TEXT "x-perl"                        ,
	"\x15" "#!/usr/bin/env python"                          , TEXT "x-python"                      ,
	"\x13" "#!/usr/bin/env ruby"                            , TEXT "x-ruby"                        ,
	"\x12" "#!/usr/bin/env tcl"                             , TEXT "x-tcl"                         ,
	"\x13" "#!/usr/bin/env wish"                            , TEXT "x-tcl"                         ,
	"\x0E" "#!/usr/bin/lua"                                 , TEXT "x-lua"                         ,
	"\x11" "#!/usr/bin/python"                              , TEXT "x-python"                      ,
	"\x0F" "#!/usr/bin/ruby"                                , TEXT "x-ruby"                        ,
	"\x0E" "#!/usr/bin/tcl"                                 , TEXT "x-tcl"                         ,
	"\x0F" "#!/usr/bin/wish"                                , TEXT "x-tcl"                         ,
	"\x14" "#!/usr/local/bin/lua"                           , TEXT "x-lua"                         ,
	"\x15" "#!/usr/local/bin/perl"                          , TEXT "x-perl"                        ,
	"\x17" "#!/usr/local/bin/python"                        , TEXT "x-python"                      ,
	"\x15" "#!/usr/local/bin/ruby"                          , TEXT "x-ruby"                        ,
	"\x14" "#!/usr/local/bin/tcl"                           , TEXT "x-tcl"                         ,
	"\x15" "#!/usr/local/bin/wish"                          , TEXT "x-tcl"                         ,
	"\x11" "# KDE Config File"                              , APPLICATION "x-kdelnk"               ,
	"\x14" "# PaCkAgE DaTaStReAm"                           , APPLICATION "x-svr4-package"         ,
	"\x06" "# xmcd"                                         , TEXT "x-xmcd"                        ,
	"\x0B" "#?RADIANCE\x0A"                                 , IMAGE "vnd.radiance"                 ,
	"\x0B" "%!PS-Adobe-"                                    , APPLICATION "postscript"             ,
	"\x05" "%PDF-"                                          , APPLICATION "pdf"                    ,
	"\x05" "*mbx*"                                          , APPLICATION "mbox"                   ,
	"\x1C" "-----BEGIN PGP MESSAGE-\x00\x1E---"             , APPLICATION "pgp"                    ,
	"\x1E" "-----BEGIN PGP SIGNATURE-\x00\x03.\""           , APPLICATION "pgp-signature"          ,
	"\x03" ".\""                                            , TEXT "troff"                         ,
	"\x04" ".sd\x00"                                        , AUDIO "x-dec-basic"                  ,
	"\x04" ".snd"                                           , AUDIO "basic"                        ,
	"\x09" "/* XPM */"                                      , IMAGE "x-xpmi"                       ,
	"\x05" "07070"                                          , APPLICATION "x-cpio"                 ,
	"\x04" "1\xBE\x00\x00"                                  , APPLICATION "msword"                 ,
	"\x06" "7z\xBC\xAF'\x1C"                                , APPLICATION "x-7z-compressed"        ,
	"\x1A" "8BPS Adobe Photoshop Image"                     , IMAGE "vnd.adobe.photoshop"          ,
	"\x04" ";ELC"                                           , APPLICATION "x-elc"                  ,
	"\x0E" "<!DOCTYPE HTML"                                 , TEXT "html"                          ,
	"\x0E" "<?xml version="                                 , APPLICATION "xml"                    ,
	"\x06" "<Book "                                         , APPLICATION "x-mif"                  ,
	"\x09" "<BookFile"                                      , APPLICATION "x-mif"                  ,
	"\x04" "<MML"                                           , APPLICATION "x-mif"                  ,
	"\x08" "<MIFFile"                                       , APPLICATION "x-mif"                  ,
	"\x10" "<MakerDictionary"                               , APPLICATION "x-mif"                  ,
	"\x06" "<Maker"                                         , APPLICATION "x-mif"                  ,
	"\x0C" "<SCRIBUSUTF8"                                   , APPLICATION "x-scribus"              ,
	"\x0C" "<map version"                                   , APPLICATION "x-freemind"             ,
	"\x0A" "@ echo off"                                     , TEXT "x-msdos-batch"                 ,
	"\x09" "@echo off"                                      , TEXT "x-msdos-batch"                 ,
	"\x04" "@rem"                                           , TEXT "x-msdos-batch"                 ,
	"\x04" "@set"                                           , TEXT "x-msdos-batch"                 ,
	"\x04" "ADIF"                                           , AUDIO "x-hx-aac-adif"                ,
	"\x08" "AT&TFORM"                                       , IMAGE "vnd.djvu"                     ,
	"\x07" "Article"                                        , MESSAGE "news"                       ,
	"\x0F" "BEGIN:VCALENDAR"                                , TEXT "calendar"                      ,
	"\x0B" "BEGIN:VCARD"                                    , TEXT "x-vcard"                       ,
	"\x04" "BM\x00\x03"                                     , IMAGE "x-ms-bmp"                     ,
	"\x03" "BZh"                                            , APPLICATION "x-bzip2"                ,
	"\x04" "CPC\xB2"                                        , IMAGE "x-cpi"                        ,
	"\x03" "CWS"                                            , APPLICATION "x-shockwave-flash"      ,
	"\x04" "DICM"                                           , APPLICATION "dicom"                  ,
	"\x04" "EIM "                                           , IMAGE "x-eim"                        ,
	"\x06" "FGF95a"                                         , IMAGE "x-unknown"                    ,
	"\x03" "FLV"                                            , VIDEO "x-flv"                        ,
	"\x04" "FOVb"                                           , IMAGE "x-x3f"                        ,
	"\x03" "FWS"                                            , APPLICATION "x-shockwave-flash"      ,
	"\x0A" "Forward to"                                     , MESSAGE "rfc822"                     ,
	"\x05" "From:"                                          , MESSAGE "rfc822"                     ,
	"\x04" "GIF8"                                           , IMAGE "gif"                          ,
	"\x06" "GIF94z"                                         , IMAGE "x-unknown"                    ,
	"\x0A" "HEADER    "                                     , CHEMICAL "x-pdb"                     ,
	"\x11" "HWP Document File"                              , APPLICATION "x-hwp"                  ,
	"\x0E" "II\x1A\x00\x00\x00HEAPCCDR"                     , IMAGE "x-canon-crw"                  ,
	"\x04" "II*\x00"                                        , IMAGE "tiff"                         ,
	"\x0A" "II*\x00\x10\x00\x00\x00CR"                      , IMAGE "x-canon-cr2"                  ,
	"\x04" "IIN1"                                           , IMAGE "x-niff"                       ,
	"\x04" "IIRO"                                           , IMAGE "x-olympus-orf"                ,
	"\x04" "IIRS"                                           , IMAGE "x-olympus-orf"                ,
	"\x04" "LRZI"                                           , APPLICATION "x-lrzip"                ,
	"\x04" "LZIP"                                           , APPLICATION "x-lzip"                 ,
	"\x0E" "MAS_UTrack_V00"                                 , AUDIO "x-mod"                        ,
	"\x04" "MM\x00*"                                        , IMAGE "tiff"                         ,
	"\x04" "MMOR"                                           , IMAGE "x-olympus-orf"                ,
	"\x04" "MOVI"                                           , VIDEO "x-sgi-movie"                  ,
	"\x04" "MThd"                                           , AUDIO "midi"                         ,
	"\x02" "MZ"                                             , APPLICATION "x-dosexec"              ,
	"\x09" "N#! rnews"                                      , MESSAGE "rfc822"                     ,
	"\x04" "OTTO"                                           , APPLICATION "vnd.ms-opentype"        ,
	"\x04" "OggS"                                           , APPLICATION "ogg"                    ,
	"\x03" "P4\x00"                                         , IMAGE "x-portable-bitmap"            ,
	"\x03" "P5\x00"                                         , IMAGE "x-portable-greymap"           ,
	"\x03" "P6\x00"                                         , IMAGE "x-portable-pixmap"            ,
	"\x03" "P7\x00"                                         , IMAGE "x-portable-pixmap"            ,
	"\x0C" "P7\n#MTPAINT#"                                  , IMAGE "x-portable-multimap"          ,
	"\x03" "PBF"                                            , IMAGE "x-unknown"                    ,
	"\x04" "PDN3"                                           , IMAGE "x-paintnet"                   ,
	"\x05" "PFS1\x0A"                                       , IMAGE "x-pfs"                        ,
	"\x04" "PK\x03\x04"                                     , APPLICATION "zip"                    ,
	"\x08" "PK\x07\x08PK\x03\x04"                           , APPLICATION "zip"                    ,
	"\x08" "PK00PK\x03\x04"                                 , APPLICATION "zip"                    ,
	"\x05" "PO^Q`"                                          , APPLICATION "msword"                 ,
	"\x05" "Path:"                                          , MESSAGE "news"                       ,
	"\x07" "Pipe to"                                        , MESSAGE "rfc822"                     ,
	"\x10" "RF64\xFF\xFF\xFF\xFFWAVEds64"                   , AUDIO "x-wav"                        ,
	"\x04" "Rar!"                                           , APPLICATION "x-rar"                  ,
	"\x09" "Received:"                                      , MESSAGE "rfc822"                     ,
	"\x0E" "Relay-Version:"                                 , MESSAGE "rfc822"                     ,
	"\x0C" "Return-Path:"                                   , MESSAGE "rfc822"                     ,
	"\x04" "SIT!"                                           , APPLICATION "x-stuffit"              ,
	"\x0D" "SplineFontDB:"                                  , APPLICATION "vnd.font-fontforge-sfd" ,
	"\x08" "StuffIt\x00"                                    , APPLICATION "x-stuffit"              ,
	"\x04" "WARC"                                           , APPLICATION "warc"                   ,
	"\x04" "Xcur"                                           , IMAGE "x-xcursor"                    ,
	"\x05" "Xref:"                                          , MESSAGE "news"                       ,
	"\x13" "[KDE Desktop Entry]"                            , APPLICATION "x-kdelnk"               ,
	"\x0B" "d8:announce"                                    , APPLICATION "x-bittorrent"           ,
	"\x04" "drpm"                                           , APPLICATION "x-rpm"                  ,
	"\x04" "fLaC"                                           , AUDIO "x-flac"                       ,
	"\x0B" "filedesc://"                                    , APPLICATION "x-ia-arc"               ,
	"\x10" "riff.\x91\xCF\x11\xA5\xD6(\xDB\x04\xC1\x00\x00" , AUDIO "x-w64"                        ,
	"\x05" "\rtf\x00"                                       , TEXT "rtf"                           ,
	"\x09" "\x89LZO\x00\x0D\x0A\x1A\x0A"                    , APPLICATION "x-lzop"                 ,
	"\x08" "\x89PNG\x0D\x0A\x1A\x0A"                        , IMAGE "png"                          ,
	"\x04" "\x8AJNG"                                        , VIDEO "x-jng"                        ,
	"\x04" "\x8AMNG"                                        , VIDEO "x-mng"                        ,
	"\x08" "\x89HDF\x0D\x0A\x1A\x0A"                        , APPLICATION "x-hdf"                  ,
	"\x04" "\xCE\xCE\xCE\xCE"                               , APPLICATION "x-java-jce-keystore"    ,
	"\x06" "\xFD""7zXZ\x00"                                 , APPLICATION "x-xz"                   ,
	"\x04" "\xFE""7\x00#"                                   , APPLICATION "msword"                 ,
	"\x02" "\xFF\xD8"                                       , IMAGE "jpeg"                         ,
	"\x04" "\xFF\xD8\xFF\xE0"                               , IMAGE "jpeg"                         ,
	"\x04" "\xFF\xD8\xFF\xEE"                               , IMAGE "jpeg"
};

static const char *const g_signatures_list4[] =
{
	"\x0D" "\x0AVersion:Vivo"             , VIDEO "vivo"                     ,
	"\x07" "#VRML V"                      , MODEL "vrml"                     ,
	"\x1C" "-BEGIN PGP PUBLIC KEY BLOCK-" , APPLICATION "pgp-keys"           ,
	"\x04" "XPR3"                         , APPLICATION "x-quark-xpress-3"   ,
	"\x04" "XPRa"                         , APPLICATION "x-quark-xpress-3"   ,
	"\x04" "free"                         , VIDEO "quicktime"                ,
	"\x07" "ftyp3g2"                      , VIDEO "3gpp2"                    ,
	"\x07" "ftyp3ge"                      , VIDEO "3gpp"                     ,
	"\x07" "ftyp3gg"                      , VIDEO "3gpp"                     ,
	"\x07" "ftyp3gp"                      , VIDEO "3gpp"                     ,
	"\x07" "ftyp3gs"                      , VIDEO "3gpp"                     ,
	"\x07" "ftypM4A"                      , AUDIO "mp4"                      ,
	"\x07" "ftypM4B"                      , VIDEO "quicktime"                ,
	"\x07" "ftypM4P"                      , VIDEO "quicktime"                ,
	"\x07" "ftypM4V"                      , VIDEO "mp4"                      ,
	"\x08" "ftypavc1"                     , VIDEO "3gpp"                     ,
	"\x08" "ftypiso2"                     , VIDEO "mp4"                      ,
	"\x08" "ftypisom"                     , VIDEO "mp4"                      ,
	"\x07" "ftypjp2"                      , IMAGE "jp2"                      ,
	"\x08" "ftypmmp4"                     , VIDEO "mp4"                      ,
	"\x08" "ftypmp41"                     , VIDEO "mp4"                      ,
	"\x08" "ftypmp42"                     , VIDEO "mp4"                      ,
	"\x08" "ftypmp7b"                     , VIDEO "mp4"                      ,
	"\x08" "ftypmp7t"                     , VIDEO "mp4"                      ,
	"\x06" "ftypqt"                       , VIDEO "quicktime"                ,
	"\x04" "idat"                         , VIDEO "quicktime"                ,
	"\x04" "idsc"                         , VIDEO "quicktime"                ,
	"\x02" "jP"                           , IMAGE "jp2"                      ,
	"\x04" "mdat"                         , VIDEO "quicktime"                ,
	"\x04" "pckg"                         , APPLICATION "x-quicktime-player" ,
	"\x04" "skip"                         , VIDEO "quicktime"                ,
	"\x04" "wide"                         , VIDEO "quicktime"
};

#define LIST_LEN(x)  ( sizeof(x) / sizeof(x[0]) - 2 )

static std::string s_mime_search(const char *const *const mimes, size_t len, const char *buf)
{
	size_t bot = 0;
	size_t top = len;

	size_t i = ((bot + top) >> 1) & ~1;
	int cmp = 0;

	for(; bot<=top and i<=len; i=((bot+top)>>1)&(~1))
	{
		cmp = memcmp(buf, mimes[i]+1, *mimes[i]);
		if( cmp == 0 )
			return mimes[i+1]; //match found

		else if( cmp > 0 )
			bot = i + 2;
		else
			top = i - 2;
	}
	return "unknown";
}

static bool s_is_text_file(std::ifstream &file)
{
	char buf[0x4000] = {0};
	file.read(buf, sizeof(buf));

	auto buf_size = file.gcount();
	std::string data(buf, buf_size);

	// UTF16 byte order marks
	if( data.starts_with("\xFE\xFF") or data.starts_with("\xFF\xFE") )
		return true;

	// Check the first 128 bytes (see shared-mime spec)
	const char *p = buf;
	const char *e = p + ( 128 < buf_size ? 128 : buf_size );

	for(; p<e; p++)
	{
		if( static_cast<char>(*p) < 32 and *p != 9 and *p != 10 and *p != 13 )
			return false;
	}
	return true;
}

#define BUF_LEN  256

static std::string mime_from_magic(std::string_view file_name)
{
	std::ifstream file(file_name.data());
	if( not file.is_open() )
		return "unknown";

	char buf[BUF_LEN] = {0};
	file.read(buf, BUF_LEN);

	auto size = file.gcount();
	if( size < BUF_LEN )
	{
		file.seekg(0, std::ios_base::beg);
		if( s_is_text_file(file) )
		{
			file.close();
			return "text/plain";
		}
		file.close();
//		return "unknwon";
	}
	auto mime_type = s_mime_search(g_signatures_list, LIST_LEN(g_signatures_list), buf);
	if( mime_type.empty() )
		mime_type = s_mime_search(g_signatures_list4, LIST_LEN(g_signatures_list4), buf + 4);
	return mime_type;
}

std::string get_mime_type(std::string_view file_name, bool magic_first)
{
	if( magic_first )
	{
		auto type = mime_from_magic(file_name);
		if( type != "unknown" )
			return type;

		auto name = libgs::file_name(file_name);
		auto pos = name.rfind('.');

		if( pos == std::string::npos )
			return type;

		auto it = g_suffix_hash.find(str_to_lower(name.substr(pos)));
		if( it == g_suffix_hash.end() )
			return type;
		return it->second;
	}
	auto name = libgs::file_name(file_name);
	auto pos = name.rfind('.');

	if( pos == std::string::npos )
		return mime_from_magic(file_name);

	auto it = g_suffix_hash.find(str_to_lower(name.substr(pos)));
	if( it == g_suffix_hash.end() )
		return mime_from_magic(file_name);
	return it->second;
}

bool is_text_file(std::string_view file_name)
{
	std::ifstream file(file_name.data());
	if( file.is_open() )
	{
		s_is_text_file(file);
		file.close();
		return true;
	}
	return false;
}

std::string get_text_file_encoding(std::string_view file_name)
{
	std::string result = "unknown";
	FILE *fp = std::fopen(file_name.data(), "rb");

	if( not fp )
		return result;

	// A is just a place holder
	unsigned char first_byte  = std::fgetc(fp);
	unsigned char second_byte = not std::feof(fp)? std::fgetc(fp) : 'A';
	unsigned char third_byte  = not std::feof(fp)? std::fgetc(fp) : 'A';
	unsigned char fourth_byte = not std::feof(fp)? std::fgetc(fp) : 'A';

	if( first_byte == 0xEF and second_byte == 0xBB and third_byte == 0xBF )
		result = "UTF-8";

	else if( first_byte == 0xFF and second_byte == 0xFE )
		result = "UTF-16LE";

	else if( first_byte == 0xFE and second_byte == 0xFF )
		result =  "UTF-16BE";

	else if( first_byte == 0xFF and second_byte == 0xFE and third_byte == 0x0 and fourth_byte == 0x0)
		result = "UTF-32LE";

	else if( first_byte == 0x00 and second_byte == 0x00 and third_byte == 0xFE and fourth_byte == 0xFF)
		result = "UTF-32BE";

	return result;
}

} //namespace libgs
