if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
	option(LIBGS_USE_LIBCXX "-- ${PRO_NAME}: Use clang libcxx." OFF)
	if (LIBGS_USE_LIBCXX)
		message(STATUS "${PRO_NAME}: Use clang libcxx.")
		add_compile_options(-stdlib=libc++)
		link_libraries(c++ c++abi)
	endif ()

	option(LIBGS_USE_LLD "-- ${PRO_NAME}: Use clang lld." OFF)
	if (LIBGS_USE_LLD)
		message(STATUS "${PRO_NAME}: Use clang lld.")
		set(CMAKE_EXE_LINKER_FLAGS -fuse-ld=lld)
	endif ()

elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
	option(LIBGS_ENABLE_LTO "-- ${PRO_NAME}: Use gnu-lto." OFF)
	if (LIBGS_ENABLE_LTO)
		message(STATUS "${PRO_NAME}: Use gnu-lto.")
		add_compile_options(-flto)
	endif ()
endif ()

if (WIN32)
	set(install_dir bin)
else ()
	if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		add_compile_options(-rdynamic)
	endif ()
	set(install_dir lib)
endif()

function(check_compiler_version CMAKE_CXX_STANDARD)

	if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
		if (CMAKE_CXX_COMPILER_VERSION LESS 17)
			message(FATAL_ERROR "The minimum version of 'Clang' required is 17.")
		endif ()
		add_compile_options(-Wall)

	elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		if (CMAKE_CXX_COMPILER_VERSION LESS 13)
			message(FATAL_ERROR "The minimum version of 'GNU' required is 13.")
		endif ()
		add_compile_options(-Wall)

	elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
		if (MSVC_VERSION LESS 1930)
			message(FATAL_ERROR "The minimum version of 'MSVC' required is 1930 (VS2022).")
		endif ()
		add_definitions(-D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0A00)
		add_compile_options(/W4 /wd4819)

	else()
		message(STATUS "Unknow compiler: " ${CMAKE_CXX_COMPILER_ID} " (" ${CMAKE_CXX_COMPILER_VERSION} ").")
	endif ()

#	set(CMAKE_CXX_STANDARD 20 PARENT_SCOPE)
	set(CMAKE_CXX_STANDARD 23 PARENT_SCOPE)

endfunction()